### PR TITLE
DB transaction format changed

### PR DESCRIPTION
**Pull request by alexole**

### CODE REVIEW

**Comment by jfonte** [comment]
dude, you're better off submitting requests to my fork https://github.com/jfonte/dbk-tools I fixed this on Oct last year and it still hasn't been accepted... https://github.com/nslater/dbk-tools/pull/4

**Comment by alexole** [comment]
Got it, thanks, found your fork after submit only :)

**Comment by nslater** [comment]
hey folks. sorry I missed this. I had notifications for the whole repo turned off for some reason. I have fixed that now

I'm just about to add support for Number26. but no longer use DBK. however, I'm considering keeping the DBK support in

would either of you you be interested in sending a PR to this repo with your changes, and helping me keep that format support up-to-date?

**Comment by jfonte** [comment]
@nslater OK. Submitted new PR and will close old one. Interesting that you switched to number26... are you using it in Germany? If yes, why did you change to it?

**Comment by nslater** [comment]
in Germany, yeah. switched because I saw my friend using the mobile app and getting real-time transaction notifications. neat experience so far

what do you wanna do with this PR? does #6 supercede this one?

**Comment by jfonte** [comment]
$6 just adds a suggestion for using pyenv to manage environment and has some comments regarding merging *beneficiary* & *details*. Other than that, they are equal.

**Comment by nslater** [comment]
okay cool. I'll do my new work on a branch and I'll wait for @alexole to respond

**Comment by alexole** [comment]
Hey guys, yes, just use #6.

**Pull request closed without merging**
